# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dba512fc5509f1b1862a3eb2a147dfedfae696b3187d628b8f399fdd822e717fe32d56603feb4892668a439fa89dbfef80f4f29b1847fd7c3f94cbf0996a8087

test:
  secret_key_base: 8d265abb5c801ec6c9afc9b8b57d3aa0f567c6d4d353d892ac9aa15f8fc5d86d02f539f20eb41ef4735b84e5057a09503484017cf7c4abb3615990bff07de4a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
